# Generated by Django 5.0.6 on 2024-07-03 18:53

import base.services
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_author_alter_book_avatar_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=base.services.get_book_avatar_upload_file, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), base.services.audio_size_validator]),
        ),
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=base.services.get_audio_upload_file, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3']), base.services.audio_size_validator]),
        ),
    ]
